### PR TITLE
feat: add extra behavior of promises from ioredis passing custom prom…

### PR DESCRIPTION
**Pull request by leandroandrade**
I'd like to add some extra behavior on ioredis promise using a external library. In this case, I've use bluebird for ilustrate what can you do.

I hope it can help.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — COMMENTED** [review]
I'm not sure about this. Bluebird solved some problems at one point, but today you are far better off sticking with the core implementation.

cc: @mcollina

**Review by mcollina — CHANGES_REQUESTED** [review]
I don't think this is needed. You can pass this through a custom promise via the use of a custom redis client.

__I would not recommend anybody to use bluebird in 2021__.

**Comment by leandroandrade** [comment]
@jsumners The idea of using Bluebird is just for tests and illustrate the possibility to do this. I think that in some usecases this can help us.

**Comment by leandroandrade** [comment]
I understand. Thanks for yours considerations and explanations.

**Pull request closed without merging**
